[build]
  command = "npm run build"
  publish = "dist"
  functions = ".netlify/functions-internal"

[functions]
  directory = ".netlify/functions-internal"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions-internal/entry"
  status = 200

[build.environment]
  NODE_VERSION = "20.17.0"

[dev]
  framework = "#auto"
  #targetPort = 3000
  port = 3000
  publish = "dist"
  autoLaunch = false 