[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/netlify/functions/entry"
  status = 200

[build.environment]
  NODE_VERSION = "20.17.0"

[dev]
  framework = "#auto"
  port = 3000
  publish = "dist"
  autoLaunch = false 