server:
  port: 3001

spring:
  application:
    name: flashcards-backend
  
  datasource:
    url: jdbc:postgresql://aws-0-us-east-2.pooler.supabase.com:6543/postgres
    username: postgres.rjxgyerudnnhwnovralo
    password: ydTPvfPjk863EZeZ
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 300000
      max-lifetime: 1200000
    
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:mySecretKey1234567890123456789012345678901234567890}
  expiration: 86400000 # 24 hours in milliseconds

# Supabase Configuration
supabase:
  url: ${SUPABASE_URL:https://rjxgyerudnnhwnovralo.supabase.co}
  anon-key: ${SUPABASE_ANON_KEY:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqeGd5ZXJ1ZG5uaHdub3ZyYWxvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyNDY0NjAsImV4cCI6MjA2MjgyMjQ2MH0.NnFuDWUIXzPCQhj_vRCHwu_RMu0qBssi7NzEnw-xxo4}

# Frontend Configuration
frontend:
  url: ${FRONTEND_URL:http://localhost:5173}

# OpenAI Configuration
openai:
  api-key: ${OPENAI_API_KEY:your-openai-api-key}
  model: gpt-3.5-turbo

# CORS Configuration
cors:
  allowed-origins: http://localhost:5173,http://localhost:3000
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true

logging:
  level:
    com.tenxcards.flashcards: DEBUG
    org.springframework.security: DEBUG

---
spring:
  config:
    activate:
      on-profile: prod
      
  datasource:
    url: jdbc:postgresql://aws-0-us-east-2.pooler.supabase.com:6543/postgres
    username: postgres.rjxgyerudnnhwnovralo
    password: ydTPvfPjk863EZeZ
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 30
      idle-timeout: 300000
      max-lifetime: 1200000
    
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

logging:
  level:
    com.tenxcards.flashcards: INFO
    org.springframework.security: WARN