/*
 * This file contains DTO and Command Model definitions derived from the API plan and the database models.
 * It ensures strong type safety and clear separation between data transfer objects and command models.
 */

// Command model for user login request
export type LoginUserCommand = {
  email: string;
  password: string;
};

// DTO for user login response
export type LoginUserResponseDTO = {
  token: string;
  user: {
    id: string; // UUID representing the user's ID
    email: string;
  };
};

// Represents a flashcard as returned by the API, based on the flashcards table in the database.
export type FlashcardDTO = {
  id: number;
  front: string;
  back: string;
  source: 'manual' | 'ai-full' | 'ai-edited';
  created_at: string;
  updated_at: string;
  generation_id?: number | null; // Optional field for AI generated flashcards
};

// Command model for creating a flashcard. Used in both single and bulk flashcard creation.
export type CreateFlashcardCommand = {
  front: string;
  back: string;
  source: 'manual' | 'ai-full' | 'ai-edited';
  generation_id?: number | null; // For AI generated flashcards, this field is populated; manual flashcards may leave it null.
};

// Command model for updating a flashcard. Note: Only 'manual' or 'ai-edited' sources are allowed for updates.
export type UpdateFlashcardCommand = {
  front: string;
  back: string;
  source: 'manual' | 'ai-edited';
};

// Pagination structure used in list endpoints.
export type PaginationDTO = {
  total: number;
  page: number;
  limit: number;
  pages: number;
};

// DTO for listing flashcards, includes an array of FlashcardDTO and pagination information.
export type ListFlashcardsResponseDTO = {
  data: FlashcardDTO[];
  pagination: PaginationDTO;
};

// Represents a flashcard proposal generated by the AI, always with source 'ai-full'.
export type FlashcardProposalDTO = {
  front: string;
  back: string;
  source: 'ai-full';
};

// Statistics provided after flashcard generation.
export type GenerationStatsDTO = {
  generated_count: number;
  generation_duration: string; // Duration in ISO 8601 format, e.g., 'PT2S'
};

// DTO for the result of flashcard generation, including proposals and generation statistics.
export type GenerationResultDTO = {
  generation_id: number;
  flashcardProposals: FlashcardProposalDTO[];
  stats: GenerationStatsDTO;
};

// Command model for generating flashcards from a block of text. Expects text between 1000 and 10000 characters.
export type GenerateFlashcardsCommand = {
  text: string;
};

export interface Generation {
  id: string;
  userId: string;
  createdAt: string;
  // Add other relevant fields later as needed
}

export type GenerationResponse = {
  generations: Generation[];
}; 